l_spanish:
 # General 
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ secondi"
 SETTING_VALUE_MINUTES: "$VALUE$ minuti"
 # Graphics
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "#T $SETTING_RENDERER$\n#!Determina quale renderer viene utilizzato."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Fa sì che il gioco e il tuo monitor abbiano la stessa frequenza di aggiornamento, riducendo lo screen tearing.\n\nDisattivarlo può migliorare le prestazioni."
 SETTING_PORTRAIT_MULTI_SAMPLING: "MultiSampling ritratti"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Usa il multisampling per l'Alpha-To-Coverage per rendere più uniforme la fusione dei capelli.\n\nImpostazioni inferiori aumentano le prestazioni."
 SETTING_MULTI_SAMPLING: "Anti-aliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!L'uso dell'anti-aliasing multisample (MSAA) rende più uniformi i bordi delle immagini.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_ANTI_ALIASING: "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!L'uso dell'anti-aliasing rende più uniformi i bordi delle immagini.\n\nSi consiglia FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Disabilitato"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Metodo di upscaling"
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Qualità upscaling"
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Qualità ultra"
 OPTION_UPSCALE_QUALITY_QUALITY: "Qualità"
 OPTION_UPSCALE_QUALITY_BALANCED: "Bilanciato"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Prestazioni"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Prestazioni ultra"
 SETTING_ANISOTROPIC_FILTERING: "Filtro texture"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!L'uso del filtro anisotropico migliora l'aspetto delle superfici texturizzate.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_FULLSCREEN_RESOLUTION: "Risoluzione"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Imposta la qualità dell'immagine del gioco.\n\nRisoluzioni inferiori possono aumentare le prestazioni.\n\n#X Una risoluzione di gioco con proporzioni non supportate può far apparire le interfacce fuori dallo schermo#!"
 SETTING_WINDOWED_RESOLUTION: "Risoluzione in finestra"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Imposta la risoluzione della finestra di gioco se il gioco è in modalità finestra.\n\nDeve essere nel formato #b NUMERO#!x#b NUMERO#!.\n\n#X Una risoluzione di gioco con proporzioni non supportate può far apparire le interfacce fuori dallo schermo#!"
 SETTING_RENDER_SCALE: "Scala di rendering"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nLa scala della risoluzione di rendering del gioco rispetto alla risoluzione principale, esclusa l'interfaccia utente.\n\nImpostazioni inferiori possono aumentare le prestazioni ma ridurranno la fedeltà complessiva, mentre superare il 100% può aumentare la fedeltà ma probabilmente peggiorerà le prestazioni."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Se il tuo computer dispone di più monitor, scegli quello che sarà utilizzato dal gioco."
 SETTING_GRAPHICS_DEVICE: "Scheda grafica"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleziona quale scheda grafica verrà utilizzata dal gioco. \n\nL'uso di una scheda grafica integrata o di un renderer software può ridurre le prestazioni."
 SETTING_SHADOW_MAP_RESOLUTION: "Qualità ombre"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina la risoluzione con cui vengono renderizzate le mappe ombra, se le ombre sono abilitate.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_DISPLAY_MODE: "Modalità schermo"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Determina come visualizzare il gioco sul tuo schermo"
 SETTING_BLOOM: "Bloom"
 SETTING_MESH_LOD_BIAS: "Qualità LOD mesh"
 SETTING_MESH_LOD_FADE: "Dissolvenza LOD mesh"
 SETTING_TERRAIN_SMOOTHING: "Smussatura terreno"
 OPTION_FULLSCREEN: "Schermo intero"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Visualizza il gioco usando l'intero schermo. L'impostazione Risoluzione cambierà la nitidezza dell'immagine."
 OPTION_WINDOWED: "Finestra"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Visualizza il gioco in una finestra. L'impostazione Risoluzione cambia le dimensioni della finestra."
 OPTION_DISABLED: "Disabilitato"
 OPTION_OFF: "Disattivato"
 OPTION_LOW: "Basso"
 OPTION_MEDIUM: "Medio"
 OPTION_HIGH: "Alto"
 OPTION_VERY_HIGH: "Molto alto"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Personalizzato"
 OPTION_DEFAULT: "Predefinito"
 SETTINGS_CATEGORY_UI: "Interfaccia"
 SETTINGS_CATEGORY_GAME: "Gioco"
 SETTING_TEXTURE_QUALITY: "Qualità texture"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nControlla la risoluzione delle texture caricate.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_QUALITY: "Preset qualità"
 SETTING_SFX: "SFX"
 SETTING_UI: "Interfaccia"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Seleziona un preset delle opzioni grafiche avanzate qui sotto.\n\nUn preset basso aumenta le prestazioni."
 SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Abilita un effetto "bloom", in cui le luci estremamente intense si propagano ad altre parti dell'immagine.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Abilita la profondità di campo per simulare l'obiettivo di una fotocamera, sfocando i punti dell'immagine fuori fuoco.\n\nDisattivarla può aumentare le prestazioni."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Abilita un effetto lens flare che appare nelle aree con forte bloom. Il bloom deve essere abilitato perché l'effetto appaia. \n\nDisattivarlo può aumentare le prestazioni."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Abilita un effetto lens flare secondario che appare nelle aree con forte bloom. Il bloom deve essere abilitato perché l'effetto appaia. \n\nDisattivarlo può aumentare le prestazioni."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Determina se l'occlusione ambientale in spazio schermo debba essere applicata alla mappa.\n\nDisattivarla può aumentare le prestazioni."
 SETTING_REFRACTION_TOOLTIP: "Determina se le rifrazioni appaiano o meno sull'acqua."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nControlla la qualità delle rifrazioni dell'acqua, se abilitate.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina il massimo livello di qualità degli oggetti della mappa, come gli edifici.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina la qualità dei LOD (livelli di dettaglio) sugli oggetti della mappa, come i modelli delle unità.\n\nImpostazioni inferiori possono aumentare le prestazioni."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Se attivato, i modelli 3D passano gradualmente tra diversi livelli di dettaglio (LOD) quando ingrandisci o riduci la visuale.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Determina come appaiono sulla mappa i nomi di città e province."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Determina se il terreno invalicabile sia incluso entro i confini di una nazione sulla mappa."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nDetermina la lingua dell'interfaccia utente."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "Email del tuo account Paradox"
 SETTING_FRAMERATE_CAP: "FPS massimo"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nFPS massimo (fotogrammi al secondo) che il gioco renderizzerà.\n\nImpostazioni inferiori possono ridurre il consumo energetico."
 OPTION_CAP_MONITOR: "Frequenza di aggiornamento del display"
 OPTION_CAP_UNCAPPED: "Frequenza di aggiornamento illimitata"
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Streaming texture"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nLe texture vengono caricate secondo necessità.\n\nRiduce l'uso della memoria GPU al costo di un certo sovraccarico di tempo CPU. Può aumentare le prestazioni per GPU con poca memoria."
 SETTING_TEXTURE_STREAMING_CACHE: "Dimensione cache streaming texture"
 SETTING_VALUE_MB: "$VALUE$ MB"
 # GUI
 SETTING_ANIMATION_SPEED: "Velocità animazione"
 SETTING_GUI_SCALING: "Ridimensionamento GUI"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Imposta la scala dell'intera interfaccia utente. Utile per risoluzioni dello schermo più alte.\n\n#X Impostarla troppo alta farà sì che le interfacce non si adattino correttamente allo schermo!#!"
 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Panoramica con mouse"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Libera"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 direzioni"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Disabilitata"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nCome si comporta la visuale durante la panoramica con il mouse."
 SETTING_SCROLL_SPEED: "Velocità panoramica"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nImposta la velocità con cui la mappa si sposta usando la tastiera o il mouse."
 SETTING_CAMERA_ROTATION_SPEED: "Velocità rotazione visuale"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nLa velocità di rotazione della visuale."
 SETTING_ZOOM_SPEED: "Velocità zoom"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nLa velocità dello zoom della visuale."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Comportamento zoom"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Cursore relativo"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Zoom verso il cursore"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignora cursore"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nCome si comporta la visuale rispetto al cursore del mouse durante lo zoom avanti/indietro."
 SETTING_INPUT_DEVICE: "Dispositivo di input"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Suffisso editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Comando apertura editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Comando visualizzazione log"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Comando apertura editor di codice"
 SETTING_GRACEFUL_EXIT: "Uscita ordinata"
 SETTING_LANGUAGE: "Lingua"
 MOUSE_AND_KEYBOARD: "Mouse e tastiera"
 GAMEPAD: "Gamepad"
 SETTING_MULTISAMPLING_DISABLED: "Disabilitato"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Disabilitato"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Disabilitato"
 # Editor
 SETTING_CAMERA_TILT: "Inclinazione visuale"
 SETTING_CAMERA_STRATEGY: "Tipo di visuale"
 SETTING_CENTERED_ZOOM_IN: "Zoom avanti centrato"
 SETTING_CAMERA_SPEED: "Velocità visuale"
 CAMERA_TABLETOP: "Da tavolo"
 CAMERA_FPS: "Prima persona"
 CAMERA_WASD: "Stile WASD"
 # Audio
 SETTING_Music: "Musica"
 SETTING_Ambient: "Ambiente"
 SETTING_Effects: "Effetti"
 SETTING_Master: "Master"
 SETTING_VO: "Voice-over"
 SETTING_VO_TOOLTIP: "#T Volume voice-over\n#!Imposta il volume del voice-over nel gioco."
 SETTING_Master_TOOLTIP: "#T Volume master\n#!Imposta il volume di tutti i suoni nel gioco."
 SETTING_Music_TOOLTIP: "#T Volume musica\n#!Imposta il volume della musica."
 SETTING_Ambient_TOOLTIP: "#T Volume ambiente\n#!Imposta il volume dell'ambienza ambientale."
 SETTING_SFX_TOOLTIP: "#T Volume SFX\n#!Imposta il volume degli effetti sonori, come quelli di combattimento."
 SETTING_UI_TOOLTIP: "#T Volume interfaccia\n#!Imposta il volume dell'interfaccia utente."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Livello log debug"
 SETTING_AUDIO_DEVICE_PROFILE: "Profilo audio"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Scegli il profilo audio adatto alla tua configurazione."
 SETTING_AUDIO_OPTION_SPEAKERS: "Altoparlanti"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Mix predefinito per $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Cuffie"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Mix regolato per $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Mix per $SETTING_AUDIO_OPTION_TV$ e altoparlanti del monitor."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Modalità notte"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Attenua il suono per il gioco notturno, smorzando le frequenze più alte e comprimendo la gamma dinamica."
 SETTING_MUSIC_DENSITY: "Densità musica"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Controlla l'equilibrio tra brani completi, silenzio e segmenti di musica d'atmosfera.\n\nIntensa = Per lo più brani riprodotti uno dopo l'altro, simile a una ‘stazione radio’.\nBilanciata = Il perfetto equilibrio tra brani, silenzio e atmosfera\nRilassata = Per lo più segmenti musicali rilassanti che offrono una migliore esperienza d'atmosfera e una minore sensazione di ripetizione dopo diverse ore di gioco"
  # Game
 SETTING_AUTOSAVE: "Intervallo salvataggio automatico"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Imposta la frequenza con cui il gioco salverà automaticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Determina se i salvataggi automatici vengano salvati sul cloud o meno."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Determina se la visuale sia sempre rivolta a nord o meno."
 NO_AUTOSAVE: "Nessun salvataggio automatico"
 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Velocità trasferimento file"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Imposta la velocità massima per i trasferimenti dei file di salvataggio nella lobby multigiocatore.\n\nImpostazioni inferiori possono migliorare la stabilità della rete per chi si unisce alle partite multigiocatore, ma hanno un effetto negativo sui tempi di caricamento multigiocatore.\n\nL'host multigiocatore determina la velocità massima.\n"
 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Salvataggio automatico editor mappa (minuti)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Intervallo salvataggio automatico editor mappa (minuti)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Modalità trascinamento panoramica editor nodi"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Modalità autocompletamento console"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Espansione completa, scorri con tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Espansione parziale fino alla differenza"
 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Accessibilità"
 SETTING_COLOR_BLIND_MODE: "Modalità daltonismo"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Cambia i colori usati nel testo in tutto il gioco con una serie di colori più facile da distinguere per diversi tipi di daltonismo."
