l_spanish:
 SETTING_REFRACTION: "Rifrazione"
 SETTING_REFRACTION_QUALITY: "Qualità rifrazione"
 SETTING_MAPOBJECT_QUALITY: "Oggetti mappa"
 SETTING_MAP_SSAO: "SSAO mappa"
 SETTING_DOF: "Profondità di campo"
 SETTING_LENS_FLARE: "Lens flare"
 SETTING_SECONDARY_LENS_FLARE: "Lens flare secondario"
